# Generated by Django 5.2.12 on 2026-04-08 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("tipo", models.CharField(max_length=80)),
                ("capacidad", models.PositiveIntegerField()),
                ("planta", models.CharField(max_length=10)),
                ("equipamiento", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "Disponible"),
                            ("Ocupada", "Ocupada"),
                            ("Mantenimiento", "Mantenimiento"),
                        ],
                        default="Disponible",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "aula",
                "verbose_name_plural": "aulas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=120)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("Baja", "Baja"),
                            ("Media", "Media"),
                            ("Alta", "Alta"),
                        ],
                        default="Media",
                        max_length=10,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Abierta", "Abierta"),
                            ("En curso", "En curso"),
                            ("Resuelta", "Resuelta"),
                        ],
                        default="Abierta",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to="gestion.aula",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "incidencia",
                "verbose_name_plural": "incidencias",
                "ordering": ["-fecha", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("profesor", "Profesor"), ("admin", "Admin")],
                        default="profesor",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("Activo", "Activo"), ("Bloqueado", "Bloqueado")],
                        default="Activo",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de usuario",
                "verbose_name_plural": "perfiles de usuario",
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("motivo", models.CharField(max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Confirmada", "Confirmada"),
                            ("Denegada", "Denegada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="gestion.aula",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reserva",
                "verbose_name_plural": "reservas",
                "ordering": ["-fecha", "hora_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("aula", "fecha", "hora_inicio", "hora_fin"),
                        name="unique_reserva_aula_franja",
                    )
                ],
            },
        ),
    ]
