# Generated by Django 5.2.10 on 2026-04-09 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reserva",
            name="unique_reserva_aula_franja",
        ),
        migrations.AddConstraint(
            model_name="reserva",
            constraint=models.UniqueConstraint(
                fields=("aula", "usuario", "fecha", "hora_inicio", "hora_fin"),
                name="unique_reserva_usuario_aula_franja",
            ),
        ),
    ]
