# Generated by Django 5.2.10 on 2026-04-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_remove_reserva_unique_reserva_aula_franja_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("En curso", "En curso"),
                    ("Resuelta", "Resuelta"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
